CREATE SEQUENCE seq_tb_ic_address START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tb_ic_analysis START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tb_ic_child START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tb_ic_exam START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tb_ic_phone START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tb_ic_user START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tb_ic_erros START WITH 1 INCREMENT BY 1;